{
 "title": "Speed Radar",
 "description": "Projekt využívajúci dáta z rýchlostného radaru mesta prešov umiestneného na ulici Soľnobanská v Solivare.",
 "tags": [
  "Solivar",
  "Presov"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Aktualne ukazovatele",
   "type": "gauge",
   "description": "Ako sa dodrziava rychlostny limit 50 km/h na Solivare",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speed",
     "query": "SELECT \"speed\" FROM \"speed\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "speed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "TOP 25",
   "type": "table",
   "description": "Najrychlejsi soferi",
   "gridPos": { "h": 19, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "speed",
     "query": "SELECT \"value\" FROM \"measurement\" WHERE $timeFilter  order by speed",
     "select": [
      [
       { "params": [ "speed" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    { "expression": "A", "reducer": "max", "type": "reduce" }
   ]
  },
  {
   "title": "Sledovanie radaru",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speed",
     "select": [
      [
       { "params": [ "speed" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Štatistické rozdelenie rýchlostí",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 9, "x": 1, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speed",
     "select": [
      [
       { "params": [ "speed" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HeatMapa",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speed",
     "select": [
      [
       { "params": [ "speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pocet Merani (aut)",
   "type": "heatmap",
   "description": "Pocet aut zaznamenaných meraní",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 32 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speed",
     "select": [
      [
       { "params": [ "speed" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  }
 ]
}